# Generated by Django 5.0.2 on 2024-03-19 10:44

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mediafiles/pet_photos', validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
